### ISSUE TITLE
No binaries for release v10010063

### ISSUE THREAD

**Issue by jonathanudd** [UniqueNetwork/unique-chain#1030]
I'm working for a RPC node provider called Dwellir and we usually download binaries from releases but there are no binaries published for the release [v10010063](https://github.com/UniqueNetwork/unique-chain/releases/tag/v10010063).

Is this intended or will the binaries be added later?

**Comment by BuddyGlas** [comment]
Thank you very much for your appeal.
We have uploaded the binary files to the release assets, as well as the images for Quartz and Unique.
