### ISSUE TITLE
Deleted items ate

### ISSUE THREAD

**Issue by GuiGou12358** [UniqueNetwork/unique-chain#342]

**Comment by GuiGou12358** [comment]
@kozyrevdev does it mean this issue is already fixed? Or is it duplicated another issue?

**Comment by kozyrevdev** [comment]
@GuiGou12358 greetings,

the issue was empty, you've just added details now. Please send an issue when it fulfilled.

Considering new details you should open issue on Unique Scan repo https://github.com/UniqueNetwork/unique-scan-backend

**Comment by GuiGou12358** [comment]
@kozyrevdev It was empty due to a wrong click. I just opened a new issue in unique-scan-backend
