### ISSUE TITLE
Suggestion: Replace polkadot-launch with Zombienet or parachain-launch

### ISSUE THREAD

**Issue by doutv** [UniqueNetwork/unique-chain#386]
See below for motivation:
- https://github.com/substrate-developer-hub/substrate-docs/issues/1098#issue-1262168919
- https://github.com/paritytech/polkadot-launch/issues/189#issue-1261901795
- https://github.com/substrate-developer-hub/substrate-docs/issues/1098#issue-1262168919

**Comment by doutv** [comment]
I tried to use [`parachain-launch`](https://github.com/open-web3-stack/parachain-launch).

There are some images here: https://hub.docker.com/u/uniquenetwork 

Maybe I can use this image? https://hub.docker.com/r/uniquenetwork/quartz-node-public

**Comment by Fahrrader** [comment]
Reviving this issue with news that we're deploying Zombienet in our CI very soon! It's been possible to use Zombienet natively or with the images you correctly pointed to, 

https://hub.docker.com/r/uniquenetwork/quartz-node-public for a Quartz node

and

https://hub.docker.com/r/uniquenetwork/unique-node-public for a Unique node.

But with [this PR](https://github.com/UniqueNetwork/unique-chain/pull/930), test network specs will appear in the root of the repository (and a whole script in `tests` to launch it), which will hopefully make it easier to get started.

**Comment by CertainLach** [comment]
We have updated our test infrastructure to use our own parachain launcher: https://github.com/uniquenetwork/baedeker, which has better integration with https://github.com/uniquenetwork/chainql, which we were using for some tasks (I.e chopstics-like parachain fork tests: https://github.com/UniqueNetwork/unique-chain/blob/master/.baedeker/forkless-data.jsonnet).
